name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --info

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@main
        with:
          organization: ${{ secrets.ORGANIZATION }}
          token: ${{ secrets.SONAR_TOKEN }}
          projectBaseDir: ./
  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --tests "api.veiculos.units.*"

  integration-tests:
    runs-on: ubuntu-latest
    needs: [build, unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run integration tests
        run: ./gradlew test --tests "api.veiculos.integration.*"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [build, unit-tests, integration-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run E2E tests
        run: ./gradlew test --tests "api.veiculos.e2e.*"

  deploy:
    needs: [unit-tests, integration-tests, e2e-tests, sonarqube-analysis]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Hello, World!"
