name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle and run SonarQube analysis
        run: ./gradlew build sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-sonarqube ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --tests "api.veiculos.units.*"

  integration-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-sonarqube , unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run integration tests
        run: ./gradlew test --tests "api.veiculos.integration.*"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [ build-and-sonarqube, unit-tests, integration-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run E2E tests
        run: ./gradlew test --tests "api.veiculos.e2e.*"

  deploy:
    needs: [unit-tests, integration-tests, e2e-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Hello, World!"
